---
title: "code"
format: html
---

```{r}
# ERR1539001_filtered.fastq.gz

path <- "/Users/abatta00/Documents/BINF4010/Week2_Yeast_Project_ab/data/clean_reads/ERR1539001_filtered.fastq.gz"

```

```{bash}
flye --pacibo-raw "/Users/abatta00/Documents/BINF4010/Week2_Yeast_Project_ab/data/clean_reads/ERR1539001_filtered.fastq.gz" --out-dir "/data/assemble_genomes" --genome-size 12m -t 8 --scaffold -i 5
```

```{bash}
# To create environment
conda create -n medaka_env -c conda-forge -c bioconda medaka -y
```

```{bash}
medaka_consensus -i fastq -d "/data/assembly_genomes/______" -o "/data/polished_genomes" -t 8 
```

```{r}
library(Gviz)
library(Rsamtools)
library(GenomicAlignments)
library(GenomicRanges)
```

```{r}
bam_file <- system.file("extdata/test.bam", package = "Gviz")
bam_file
```

```{r}
a <- idxstatsBam(bam_file)
```

```{r}
# Create a GRanges object from the BAM file
alignment_ranges <- bam_file |> readGAlignments() |> GRanges()

# Find the start and end boundaries of all reads combined
range(alignment_ranges)
```

```{r}
# Peek at the individual read boundaries
ranges(alignment_ranges)
```
